name: Ucoe
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  curved_navigation_bar: ^0.3.7
  user_profile_avatar: ^0.0.9
  circular_profile_avatar: ^1.0.8
  #old working
  # firebase_database: ^3.0.0
  #new 
  firebase_database: ^4.2.0
  #new
  firebase_auth: ^0.18.1

  #new
  firebase_storage : ^5.0.0
  #old working
  animated_text_kit: ^4.1.1
  
  # firebase_auth: ^0.14.0+5
  #new
  firebase_core: ^0.5.0+1
  #new
  cloud_firestore: ^0.14.1+3
  #old working
  # cloud_firestore: ^0.12.11
  #old working
  # firebase_core : ^0.4.3
  #old working
  # firebase_storage : ^3.1.6
  fluttertoast: ^7.1.6
  email_validator: ^1.0.6
  # image_picker: ^0.6.7+17
  permission_handler: ^5.0.1+1
  image_picker: ^0.6.7+22
  random_string: ^2.1.0
  video_player: ^0.10.1
  # shared_preferences: ^0.5.6+3
  shared_preferences: ^2.0.5
  flutter_spinkit: ^4.1.2+1
  cached_network_image: ^2.2.0+1
  carousel_pro: ^1.0.0
  carousel_slider: ^3.0.0
  # file_picker: ^2.1.7
  file_picker: ^1.9.0+1
  google_fonts: ^1.1.2

  flip_card: ^0.4.4
  audioplayer: ^0.8.1
  flutter_launcher_icons: ^0.9.0
  firebase_messaging: ^7.0.3
  provider: ^4.0.2
  http: ^0.12.0
  salomon_bottom_bar: ^3.0.0
  flutter_downloader: ^1.5.2
  emoji_picker: ^0.0.1
  path_provider : ^2.0.0
  url_launcher: ^6.0.3
  dio: ^3.0.0
  flutter_local_notifications: ^4.0.0
  open_file: ^3.1.0
  downloads_path_provider_28: ^0.1.0
  google_maps_flutter: ^0.5.21+15
  location: ^2.3.5
  google_map_polyline: ^0.2.0+1
  flutter_polyline_points: ^0.1.0
  geocoder: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
